### ISSUE TITLE
Something wrong in S transform

### ISSUE THREAD

**Issue by xichaoqiang** [eng-tools/eqsig#1]
I try change your test_motion_dt0p01.txt with delete the '-' from line3.(as show in the attachment)

the abs_error is very big but almost the same number(15182.16315542 ).
[test_motion_dt0p01.txt](https://github.com/eng-tools/eqsig/files/3812584/test_motion_dt0p01.txt)

```
import numpy as np

from eqsig.single import AccSignal
from conftest import TEST_DATA_DIR
from eqsig import stockwell
from eqsig.functions import interp_to_approx_dt


def test_stockwell_transform_then_inverse():
    record_path = TEST_DATA_DIR
    record_filename = 'test_motion_dt0p01.txt'
    motion_step = 0.01
    rec = np.loadtxt(record_path + record_filename, skiprows=2)
    acc_signal = AccSignal(rec, motion_step)
#    acc2_signal = interp_to_approx_dt(acc_signal, 0.1)
    acc_signal.swtf = stockwell.transform(acc_signal.values, interp=True)
    assert len(acc_signal.swtf[0]) == 2 * acc_signal.npts
    inv_signal = AccSignal(stockwell.itransform(acc_signal.swtf), acc_signal.dt)

    abs_error = abs(acc_signal.values - inv_signal.values)
    print("")
    assert np.sum(abs_error) / acc1_signal.npts < 0.001, np.sum(abs_error)
test_stockwell_transform_then_inverse()
```

**Comment by millen1m** [comment]
By removing the negative sign in front of the exponential you are creating a non-baseline-corrected record - you should plot the record to see. The S-transform assumes a zero average response, what you would get for a normal ground motion recording. I would suggest you try with another recorded ground motion.

**Comment by xichaoqiang** [comment]
> By removing the negative sign in front of the exponential you are creating a non-baseline-corrected record - you should plot the record to see. The S-transform assumes a zero average response, what you would get for a normal ground motion recording. I would suggest you try with another recorded ground motion.

Thank you. I have try some other S-transform and inverse  S-transform code by 
signal  x=np.linspace(1,11,11),
st0= st(x)
ts0= ist(st0)
the ts0 is almost same to raw signal x, with error about 1e-8.

**Comment by millen1m** [comment]
Great.
